(** The simulation SoC: the core with the boot ROM ({!Rom}), 1 MiB of single-cycle RAM and
    the peripherals, under RISC5Top's address decode and MMIO map. It is what the boot
    gates run on the Cyclesim interpreter.

    {1 Address decode}

    Three regions, as RISC5Top has them:
    - fetch: [codebus] comes from the ROM when [adr[23:14] = 0x3FF], the top 16 KiB, and
      from RAM otherwise;
    - load: [inbus] comes from the peripherals when [adr[23:6] = 0x3FFFF], the top 64
      bytes, and from RAM otherwise;
    - store: the RAM takes the core's write directly. The original's SRAM has no MMIO
      gate, so a store to a peripheral or to the ROM region also lands in the aliased RAM
      word, harmlessly.

    {1 Video, timer, interrupt}

    The video controller ({!Video}) drives the core's [stall_x]: every 32 pixels its DMA
    request steals one cycle of the RAM port to read a framebuffer word.

    The interrupt and the millisecond counter come from one free-running timer.

    {1 MMIO map}

    The sixteen words of the load window:
    - {b 0}: the millisecond counter.
    - {b 1}: reads [{btn, sw}] (all off, the default, boots from disk); a store latches
      the LEDs.
    - {b 2, 3}: the UART ({!Uart_rx}, {!Uart_tx}). Word 2 receives and transmits a byte;
      word 3 reads the status [{rdyTx, rdyRx}] and writes the rate bit.
    - {b 4, 5}: the {!Spi} master, the one peripheral booting needs. Word 4 is the data (a
      write starts a transfer); word 5 writes the control register and reads [rdy]. The SD
      card is outside the design: [miso] is an input, [mosi] and [sclk] outputs.
    - {b 6, 7}: the PS/2 keyboard and mouse ({!Ps2}, {!Mouse}). Word 6 reads
      [{keyboard ready, mouse state}]; word 7 reads a keyboard byte and pops its FIFO.
    - {b 8, 9}: GPIO: the drive value and the direction; reading word 8 returns the pins.
    - {b 10..15}: unmapped; they read 0.

    {1 Parameters}

    [~contents] is the boot ROM image. [~clocks_per_ms] defaults to 25000, 1 ms at 25 MHz.
    [?spi_slow_div_log2] is {!Spi}'s slow divider depth, 6 by default; the boot gates'
    fast mode passes 2. *)

open Hardcaml

module I : sig
  type 'a t =
    { clock : 'a (** system clock (the 25 MHz core/memory domain) *)
    ; rst_n : 'a (** active-low reset (the core's [rst]) *)
    ; miso : 'a (** SPI master-in slave-out — the already-ANDed SD/net line *)
    ; rxd : 'a (** RS-232 receive line; idles high *)
    ; btn : 'a (** buttons (RISC5Top [btn]); read-only via MMIO word 1 *)
    ; sw : 'a (** switches, logical/active-high (RISC5Top's [~nswi], de-inverted) *)
    ; gpio_in : 'a (** resolved GPIO pad inputs (RISC5Top [gpin]) *)
    ; pclk : 'a (** 65 MHz pixel clock for {!Video}, generated by the board *)
    ; ps2c : 'a (** PS/2 keyboard clock *)
    ; ps2d : 'a (** PS/2 keyboard data *)
    ; msclk : 'a (** PS/2 mouse clock — resolved open-drain line in *)
    ; msdat : 'a (** PS/2 mouse data — resolved open-drain line in *)
    }
  [@@deriving hardcaml]
end

module O : sig
  type 'a t =
    { adr : 'a (** 24-bit core byte address (fetch, or the load/store data address) *)
    ; rd : 'a (** core read strobe (load cycle) *)
    ; wr : 'a (** core write strobe (store cycle) *)
    ; ben : 'a (** byte enable — byte vs word access *)
    ; outbus : 'a (** store data (the core's write bus) *)
    ; codebus : 'a (** instruction-fetch read data — ROM or RAM, per the fetch decode *)
    ; inbus : 'a (** load read data — MMIO or RAM, per the load decode *)
    ; mosi : 'a (** SPI master-out slave-in *)
    ; sclk : 'a (** SPI serial clock *)
    ; txd : 'a (** RS-232 transmit line; idles high *)
    ; leds : 'a (** the 8 LEDs (RISC5Top [leds] = the [Lreg] latch, word 1) *)
    ; gpio_out : 'a (** GPIO drive value (RISC5Top [gpout], word 8) *)
    ; gpio_oe : 'a (** GPIO output-enable / direction (RISC5Top [gpoc], word 9) *)
    ; hsync : 'a (** VGA horizontal sync (active low) *)
    ; vsync : 'a (** VGA vertical sync (active low) *)
    ; rgb : 'a (** 1 bpp pixel replicated across the 6 RGB pins *)
    ; msclk_oe : 'a (** mouse [msclk] open-drain: 1 = host pulls low (request-to-send) *)
    ; msdat_oe : 'a (** mouse [msdat] open-drain: 1 = host pulls low (command bit) *)
    }
  [@@deriving hardcaml]
end

val create
  :  contents:int array
  -> ?clocks_per_ms:int
  -> ?spi_slow_div_log2:int
  -> Signal.t I.t
  -> Signal.t O.t
