(* The contract is in [soc.mli].

   [adr], [codebus] and [inbus] form a loop that the core's registers break: [adr] is
   combinational in registered state, the memories read combinationally, and the two buses
   reach [IR] and the register file only at the next edge. So the buses are wires,
   assigned after the core is built. *)

(* bind the machine's RAM (lib/ram.ml) before the opens — [open Hardcaml] shadows the bare
   sibling name with [Hardcaml.Ram] (the BRAM primitive helpers) — and rebind after *)
module Machine_ram = Ram
open! Base
open Hardcaml
open Signal
module Ram = Machine_ram

module I = struct
  type 'a t =
    { clock : 'a
    ; rst_n : 'a [@bits 1]
    ; miso : 'a [@bits 1]
    ; rxd : 'a [@bits 1] (* RS-232 receive line; idles high *)
    ; btn : 'a [@bits 4] (* buttons (RISC5Top [btn]); read-only via word 1 *)
    ; sw : 'a
         [@bits 8] (* switches, logical/active-high (RISC5Top's [~nswi], de-inverted) *)
    ; gpio_in : 'a [@bits 8] (* resolved GPIO pad inputs (RISC5Top [gpin]) *)
    ; pclk : 'a [@bits 1] (* 65 MHz pixel clock, generated by the board *)
    ; ps2c : 'a [@bits 1] (* PS/2 keyboard clock *)
    ; ps2d : 'a [@bits 1] (* PS/2 keyboard data *)
    ; msclk : 'a [@bits 1] (* PS/2 mouse clock — resolved open-drain line in *)
    ; msdat : 'a [@bits 1] (* PS/2 mouse data — resolved open-drain line in *)
    }
  [@@deriving hardcaml]
end

module O = struct
  type 'a t =
    { adr : 'a [@bits 24]
    ; rd : 'a [@bits 1]
    ; wr : 'a [@bits 1]
    ; ben : 'a [@bits 1]
    ; outbus : 'a [@bits 32]
    ; codebus : 'a [@bits 32]
    ; inbus : 'a [@bits 32]
    ; mosi : 'a [@bits 1]
    ; sclk : 'a [@bits 1]
    ; txd : 'a [@bits 1] (* RS-232 transmit line; idles high *)
    ; leds : 'a [@bits 8] (* RISC5Top [leds] = the [Lreg] latch *)
    ; gpio_out : 'a [@bits 8] (* GPIO drive value (RISC5Top [gpout]) *)
    ; gpio_oe : 'a [@bits 8] (* GPIO output-enable / direction (RISC5Top [gpoc]) *)
    ; hsync : 'a [@bits 1] (* VGA horizontal sync (active low) *)
    ; vsync : 'a [@bits 1] (* VGA vertical sync (active low) *)
    ; rgb : 'a [@bits 6] (* 1 bpp pixel replicated across the 6 RGB pins *)
    ; msclk_oe : 'a
         [@bits 1] (* mouse msclk open-drain: 1 = host pulls low (req-to-send) *)
    ; msdat_oe : 'a [@bits 1]
    (* mouse msdat open-drain: 1 = host pulls low (command bit) *)
    }
  [@@deriving hardcaml]
end

let create ~contents ?(clocks_per_ms = 25000) ?spi_slow_div_log2 (i : _ I.t) : _ O.t =
  (* [irq] closes a loop of the same kind with the peripherals, which are built after the
     core: it comes straight from the timer's register. *)
  let codebus = wire 32 in
  let inbus = wire 32 in
  let irq = wire 1 in
  (* [inv] is switch 7. [viddata] is the RAM's read bus, assigned once the RAM exists. *)
  let viddata = wire 32 in
  let vid =
    Video.create { Video.I.clk = i.clock; pclk = i.pclk; inv = bit i.sw ~pos:7; viddata }
  in
  let vidreq = vid.req -- "vidreq" in
  let vidadr = vid.vidadr -- "vidadr" in
  (* [vidreq] is the core's [stallX]: for one cycle in every 32 pixels the core is frozen
     and the RAM port is steered to the framebuffer word. The core gates [wr] off while
     stalled, so the unconditional RAM write cannot land at [vidadr]. *)
  let core =
    Cpu.create
      { Cpu.I.clock = i.clock; rst_n = i.rst_n; irq; stall_x = vidreq; inbus; codebus }
  in
  let prom = Rom.create ~contents { Rom.I.adr = select core.adr ~high:10 ~low:2 } in
  (* [vidadr] is a word address and the RAM takes a byte address *)
  let sram_adr =
    mux2 vidreq (vidadr @: zero 2) (select core.adr ~high:19 ~low:0) -- "sram_adr"
  in
  let ram =
    Ram.create
      { Ram.I.clock = i.clock
      ; adr = sram_adr
      ; wr = core.wr
      ; ben = core.ben
      ; wdata = core.outbus
      }
  in
  assign viddata ram.rdata;
  (* the ROM window: the top 16 KiB of the 24-bit map — [adr[23:14]] of the reset vector's
     byte address ([Cpu.start_adr] is a word address: <<2 then >>14 = >>12) *)
  let rom_region = select core.adr ~high:23 ~low:14 ==:. Cpu.start_adr lsr 12 in
  let ioenb = select core.adr ~high:23 ~low:6 ==:. 0x3FFFF in
  let iowadr = select core.adr ~high:5 ~low:2 in
  let per =
    Peripherals.create
      ~clocks_per_ms
      ?slow_div_log2:spi_slow_div_log2
      { Peripherals.I.clock = i.clock
      ; rst_n = i.rst_n
      ; wr = core.wr
      ; rd = core.rd
      ; ioenb
      ; iowadr
      ; outbus = core.outbus
      ; miso = i.miso
      ; rxd = i.rxd
      ; btn = i.btn
      ; sw = i.sw
      ; gpio_in = i.gpio_in
      ; ps2c = i.ps2c
      ; ps2d = i.ps2d
      ; msclk = i.msclk
      ; msdat = i.msdat
      }
  in
  assign irq per.ms_tick;
  (* fetch: ROM in the top 16 KiB, else RAM; load: MMIO in the top 64 B, else RAM *)
  assign codebus (mux2 rom_region prom.data ram.rdata);
  assign inbus (mux2 ioenb per.io_data ram.rdata);
  { O.adr = core.adr
  ; rd = core.rd
  ; wr = core.wr
  ; ben = core.ben
  ; outbus = core.outbus
  ; codebus
  ; inbus
  ; mosi = per.mosi
  ; sclk = per.sclk
  ; txd = per.txd
  ; leds = per.leds
  ; gpio_out = per.gpio_out
  ; gpio_oe = per.gpio_oe
  ; hsync = vid.hsync
  ; vsync = vid.vsync
  ; rgb = vid.rgb
  ; msclk_oe = per.msclk_oe
  ; msdat_oe = per.msdat_oe
  }
;;

(* ── Tests ── Small programs in the ROM, run on the interpreter and read back through the
   core's register file, by name. Reset goes to StartAdr, word 0x3FF800, which is byte
   0xFFE000, the ROM's first word. *)

let%expect_test "soc — fetch ROM, store + load round-trip through RAM" =
  let module Sim = Cyclesim.With_interface (I) (O) in
  let nop = 0x40080000 (* ADD R0,R0,#0 *) in
  let prog =
    [| 0x41000055 (* MOV R1, #0x55 *)
     ; 0xA1000100 (* ST R1, [R0+0x100] *)
     ; 0x82000100 (* LD R2, [R0+0x100] *)
     ; nop
     ; nop
     ; nop
     ; nop
     ; nop
    |]
  in
  let sim = Sim.create ~config:Cyclesim.Config.trace_all (create ~contents:prog) in
  let inp = Cyclesim.inputs sim in
  let regfile = Option.value_exn (Cyclesim.lookup_mem_by_name sim "regfile") in
  inp.rst_n := Bits.of_unsigned_int ~width:1 0;
  Cyclesim.cycle sim;
  inp.rst_n := Bits.of_unsigned_int ~width:1 1;
  for _ = 1 to 20 do
    Cyclesim.cycle sim
  done;
  let r k = Cyclesim.Memory.to_int regfile ~address:k in
  Stdlib.Printf.printf "R1=0x%X  R2=0x%X\n" (r 1) (r 2);
  [%expect {| R1=0x55  R2=0x55 |}]
;;

let%expect_test "soc — millisecond timer ticks cnt1 every clocks_per_ms cycles" =
  let module Sim = Cyclesim.With_interface (I) (O) in
  let nop = 0x40080000 in
  let sim =
    Sim.create
      ~config:Cyclesim.Config.trace_all
      (create ~contents:(Array.create ~len:8 nop))
  in
  let inp = Cyclesim.inputs sim in
  let cnt1 = Option.value_exn (Cyclesim.lookup_reg_by_name sim "cnt1") in
  inp.rst_n := Bits.of_unsigned_int ~width:1 0;
  Cyclesim.cycle sim;
  inp.rst_n := Bits.of_unsigned_int ~width:1 1;
  for _ = 1 to 60000 do
    Cyclesim.cycle sim
  done;
  (* default 25000 clocks/ms ⇒ ticks at 25000 and 50000; 60001 total cycles ⇒ cnt1 = 2 *)
  Stdlib.Printf.printf "cnt1 = %d\n" (Cyclesim.Reg.to_int cnt1);
  [%expect {| cnt1 = 2 |}]
;;

(* The millisecond counter must run through a reset. RISC5Top's counters have no reset
   term (lines 139-140), and Extended Oberon relies on that: after the reset button it
   resumes tasks by their saved time stamps, so [Kernel.Time()] must never go backwards. *)

let%expect_test "soc — ms timer free-runs across a mid-run reset (RISC5Top fidelity)" =
  let module Sim = Cyclesim.With_interface (I) (O) in
  let nop = 0x40080000 in
  let sim =
    Sim.create
      ~config:Cyclesim.Config.trace_all
      (create ~contents:(Array.create ~len:8 nop) ~clocks_per_ms:10)
  in
  let inp = Cyclesim.inputs sim in
  let cnt1 = Option.value_exn (Cyclesim.lookup_reg_by_name sim "cnt1") in
  let rst v = inp.rst_n := Bits.of_unsigned_int ~width:1 v in
  let run n =
    for _ = 1 to n do
      Cyclesim.cycle sim
    done
  in
  rst 0;
  run 1;
  rst 1;
  run 55;
  let before = Cyclesim.Reg.to_int cnt1 in
  (* the button: reset asserted mid-run, long enough to span several would-be ticks *)
  rst 0;
  run 27;
  let at_release = Cyclesim.Reg.to_int cnt1 in
  rst 1;
  run 29;
  let after = Cyclesim.Reg.to_int cnt1 in
  (* 10 clocks/ms ⇒ a tick every 10th clock regardless of rst_n: 56 cycles = 5, 83 = 8
     (three ticks land INSIDE the asserted reset), 112 = 11. A reset term on cnt0/cnt1
     would restart the count and fail here. *)
  Stdlib.Printf.printf "cnt1: before=%d at-release=%d after=%d\n" before at_release after;
  [%expect {| cnt1: before=5 at-release=8 after=11 |}]
;;

let%expect_test "soc — ms timer monotonic across random mid-run resets [qcheck]" =
  let module Sim = Cyclesim.With_interface (I) (O) in
  let nop = 0x40080000 in
  (* one sim for all cases; [cnt1] never resets, so each case checks the change from its
     own start: never decreasing, and in total the elapsed clocks over the prescaler,
     rounded either way *)
  let sim =
    Sim.create
      ~config:Cyclesim.Config.trace_all
      (create ~contents:(Array.create ~len:8 nop) ~clocks_per_ms:7)
  in
  let inp = Cyclesim.inputs sim in
  let cnt1 = Option.value_exn (Cyclesim.lookup_reg_by_name sim "cnt1") in
  Test_gen.check_exn
    (QCheck.Test.make
       ~count:200
       ~name:"timer free-run under reset"
       QCheck.(triple (int_bound 40) (int_bound 29) (int_bound 40))
       (fun (pre, dur0, post) ->
         let dur = dur0 + 1 in
         let start = Cyclesim.Reg.to_int cnt1 in
         let prev = ref start in
         let mono = ref true in
         let step rstv n =
           inp.rst_n := Bits.of_unsigned_int ~width:1 rstv;
           for _ = 1 to n do
             Cyclesim.cycle sim;
             let v = Cyclesim.Reg.to_int cnt1 in
             if v < !prev then mono := false;
             prev := v
           done
         in
         step 1 pre;
         step 0 dur;
         step 1 post;
         let delta = !prev - start in
         let expected = (pre + dur + post) / 7 in
         !mono && (delta = expected || delta = expected + 1)));
  [%expect {| |}]
;;

let%expect_test "soc — MMIO read mux: word 0 = ms counter, RAM elsewhere" =
  let module Sim = Cyclesim.With_interface (I) (O) in
  let nop = 0x40080000 in
  let prog =
    [| 0x43000055 (* MOV R3, #0x55 *)
     ; 0xA3000100 (* ST R3, [R0+0x100] : RAM[0x100] := 0x55 *)
     ; 0x82000100 (* LD R2, [R0+0x100] : R2 := RAM (RAM path) *)
     ; 0x640000FF (* MOV' R4, #0xFF<<16 : R4 := 0xFF0000 *)
     ; 0x4446FFC0 (* IOR R4, R4, #0xFFC0 : R4 := 0xFFFFC0 *)
     ; 0x81400000 (* LD R1, [R4] : R1 := MMIO word 0 = cnt1 (IO path) *)
     ; nop
     ; nop
     ; nop
     ; nop
    |]
  in
  (* small prescaler so cnt1 is non-zero by the IO load — proving R1 came from the timer *)
  let sim =
    Sim.create ~config:Cyclesim.Config.trace_all (create ~contents:prog ~clocks_per_ms:4)
  in
  let inp = Cyclesim.inputs sim in
  let regfile = Option.value_exn (Cyclesim.lookup_mem_by_name sim "regfile") in
  inp.rst_n := Bits.of_unsigned_int ~width:1 0;
  Cyclesim.cycle sim;
  inp.rst_n := Bits.of_unsigned_int ~width:1 1;
  for _ = 1 to 20 do
    Cyclesim.cycle sim
  done;
  let r k = Cyclesim.Memory.to_int regfile ~address:k in
  Stdlib.Printf.printf "R2 (RAM load) = 0x%X   R1 (MMIO word 0 = cnt1) = %d\n" (r 2) (r 1);
  [%expect {| R2 (RAM load) = 0x55   R1 (MMIO word 0 = cnt1) = 2 |}]
;;

let%expect_test "soc — SPI slow byte transfer (loopback) via MMIO words 4/5" =
  let module Sim = Cyclesim.With_interface (I) (O) in
  (* A boot-style SPI exchange: start a transfer (store to word 4), poll [rdy] (load word
     5 until non-zero), then read the received byte (load word 4). The SD card is modelled
     as a loopback (MISO echoes MOSI), so the received byte equals the transmitted 0xA5. *)
  let prog =
    [| 0x5100FFD0 (* MOV R1, #0xFFD0 ; R1 = -48 (SPI data) *)
     ; 0x5200FFD4 (* MOV R2, #0xFFD4 ; R2 = -44 (SPI ctrl/status) *)
     ; 0x400000A5 (* MOV R0, #0xA5 *)
     ; 0xA0100000 (* ST R0, [R1] ; start transfer, dataTx = 0xA5 (spiCtrl=0 => slow) *)
     ; 0x83200000 (* LD  R3, [R2]      ; R3 = {31'b0, rdy}; Z = (rdy == 0)   <-- poll *)
     ; 0xE1FFFFFE (* BEQ -2 ; while rdy == 0, loop *)
     ; 0x84100000 (* LD R4, [R1] ; R4 = SPI data_rx = 0xA5 (loopback) *)
     ; 0x40080000 (* nop *)
    |]
  in
  let sim = Sim.create ~config:Cyclesim.Config.trace_all (create ~contents:prog) in
  let inp = Cyclesim.inputs sim in
  let outp = Cyclesim.outputs sim in
  let regfile = Option.value_exn (Cyclesim.lookup_mem_by_name sim "regfile") in
  inp.rst_n := Bits.of_unsigned_int ~width:1 0;
  inp.miso := Bits.of_unsigned_int ~width:1 1;
  Cyclesim.cycle sim;
  inp.rst_n := Bits.of_unsigned_int ~width:1 1;
  (* slow byte = 8 bits × clk÷64 = 512 cycles, plus setup + the poll loop *)
  for _ = 1 to 800 do
    inp.miso := !(outp.mosi);
    Cyclesim.cycle sim
  done;
  let r k = Cyclesim.Memory.to_int regfile ~address:k in
  Stdlib.Printf.printf "R4 (SPI data_rx, loopback of 0xA5) = 0x%X\n" (r 4);
  [%expect {| R4 (SPI data_rx, loopback of 0xA5) = 0xA5 |}]
;;

let%expect_test "soc — word 1: read {btn, sw}; store latches the LEDs" =
  let module Sim = Cyclesim.With_interface (I) (O) in
  let nop = 0x40080000 in
  let prog =
    [| 0x640000FF (* MOV' R4, #0xFF<<16 R4 = 0xFF0000 *)
     ; 0x4446FFC4 (* IOR R4, R4, #0xFFC4 R4 = 0xFFFFC4 (word 1) *)
     ; 0x82400000 (* LD   R2, [R4]          R2 = {btn, sw} *)
     ; 0x430000AB (* MOV R3, #0xAB *)
     ; 0xA3400000 (* ST R3, [R4] Lreg := 0xAB *)
     ; nop
     ; nop
     ; nop
    |]
  in
  let sim = Sim.create ~config:Cyclesim.Config.trace_all (create ~contents:prog) in
  let inp = Cyclesim.inputs sim in
  let outp = Cyclesim.outputs sim in
  let regfile = Option.value_exn (Cyclesim.lookup_mem_by_name sim "regfile") in
  inp.rst_n := Bits.of_unsigned_int ~width:1 0;
  inp.sw := Bits.of_unsigned_int ~width:8 0x0F;
  inp.btn := Bits.of_unsigned_int ~width:4 0x5;
  Cyclesim.cycle sim;
  inp.rst_n := Bits.of_unsigned_int ~width:1 1;
  for _ = 1 to 20 do
    Cyclesim.cycle sim
  done;
  let r k = Cyclesim.Memory.to_int regfile ~address:k in
  (* {btn=5, sw=0x0F} = (5<<8) | 0x0F = 0x50F; the store latched 0xAB onto the LEDs *)
  Stdlib.Printf.printf
    "R2 (switches {btn,sw}) = 0x%X   leds = 0x%X\n"
    (r 2)
    (Bits.to_unsigned_int !(outp.leds));
  [%expect {| R2 (switches {btn,sw}) = 0x50F   leds = 0xAB |}]
;;

let%expect_test "soc — GPIO words 8/9: gpout/gpoc registers + gpin readback" =
  let module Sim = Cyclesim.With_interface (I) (O) in
  let nop = 0x40080000 in
  let prog =
    [| 0x640000FF (* MOV' R4, #0xFF<<16 R4 = 0xFF0000 *)
     ; 0x4546FFE4 (* IOR R5, R4, #0xFFE4 R5 = 0xFFFFE4 (word 9) *)
     ; 0x4446FFE0 (* IOR R4, R4, #0xFFE0 R4 = 0xFFFFE0 (word 8) *)
     ; 0x410000FF (* MOV R1, #0xFF *)
     ; 0xA1500000 (* ST R1, [R5] gpoc := 0xFF (all drive) *)
     ; 0x4200003C (* MOV R2, #0x3C *)
     ; 0xA2400000 (* ST R2, [R4] gpout := 0x3C *)
     ; 0x83400000 (* LD R3, [R4] R3 = gpin, the pin input (word 8 read) *)
     ; 0x86500000 (* LD R6, [R5] R6 = gpoc readback (word 9 read) *)
     ; nop
     ; nop
     ; nop
    |]
  in
  let sim = Sim.create ~config:Cyclesim.Config.trace_all (create ~contents:prog) in
  let inp = Cyclesim.inputs sim in
  let outp = Cyclesim.outputs sim in
  let regfile = Option.value_exn (Cyclesim.lookup_mem_by_name sim "regfile") in
  inp.rst_n := Bits.of_unsigned_int ~width:1 0;
  (* the pin input is independent of what we drive — word-8 read returns it verbatim *)
  inp.gpio_in := Bits.of_unsigned_int ~width:8 0x5A;
  Cyclesim.cycle sim;
  inp.rst_n := Bits.of_unsigned_int ~width:1 1;
  for _ = 1 to 24 do
    Cyclesim.cycle sim
  done;
  let r k = Cyclesim.Memory.to_int regfile ~address:k in
  Stdlib.Printf.printf
    "gpio_out=0x%X gpio_oe=0x%X   R3(gpin read)=0x%X R6(gpoc read)=0x%X\n"
    (Bits.to_unsigned_int !(outp.gpio_out))
    (Bits.to_unsigned_int !(outp.gpio_oe))
    (r 3)
    (r 6);
  [%expect {| gpio_out=0x3C gpio_oe=0xFF   R3(gpin read)=0x5A R6(gpoc read)=0xFF |}]
;;

let%expect_test "soc — reset clears the RISC5Top-faithful register set, and only it" =
  (* RISC5Top (lines 138-144) clears the LED latch, [spiCtrl], the UART rate bit and
     [gpoc] on reset, and deliberately neither [gpout] nor the timer. Everything is set by
     a program and then sampled while reset is held: after release the core restarts and
     runs the program again. (The rate bit has no traced name and is not sampled.) *)
  let module Sim = Cyclesim.With_interface (I) (O) in
  let nop = 0x40080000 in
  let prog =
    [| 0x640000FF (* MOV' R4, #0xFF<<16 R4 = 0xFF0000 *)
     ; 0x4546FFC4 (* IOR R5, R4, #0xFFC4 R5 = word 1 (LEDs) *)
     ; 0x4746FFD4 (* IOR R7, R4, #0xFFD4 R7 = word 5 (spiCtrl) *)
     ; 0x4846FFE0 (* IOR R8, R4, #0xFFE0 R8 = word 8 (gpout) *)
     ; 0x4946FFE4 (* IOR R9, R4, #0xFFE4 R9 = word 9 (gpoc) *)
     ; 0x410000AB (* MOV R1, #0xAB *)
     ; 0xA1500000 (* ST R1, [R5] Lreg := 0xAB *)
     ; 0x42000005 (* MOV R2, #0x5 *)
     ; 0xA2700000 (* ST R2, [R7] spiCtrl := 0x5 *)
     ; 0x4300003C (* MOV R3, #0x3C *)
     ; 0xA3800000 (* ST R3, [R8] gpout := 0x3C *)
     ; 0x410000FF (* MOV R1, #0xFF *)
     ; 0xA1900000 (* ST R1, [R9] gpoc := 0xFF *)
     ; nop
     ; nop
     ; nop
    |]
  in
  let sim =
    Sim.create ~config:Cyclesim.Config.trace_all (create ~contents:prog ~clocks_per_ms:10)
  in
  let inp = Cyclesim.inputs sim in
  let outp = Cyclesim.outputs sim in
  let spi_ctrl = Option.value_exn (Cyclesim.lookup_reg_by_name sim "spi_ctrl") in
  let cnt1 = Option.value_exn (Cyclesim.lookup_reg_by_name sim "cnt1") in
  let show tag =
    Stdlib.Printf.printf
      "%s leds=0x%X spi_ctrl=0x%X gpoc=0x%X | survivors: gpout=0x%X cnt1=%d\n"
      tag
      (Bits.to_unsigned_int !(outp.leds))
      (Cyclesim.Reg.to_int spi_ctrl)
      (Bits.to_unsigned_int !(outp.gpio_oe))
      (Bits.to_unsigned_int !(outp.gpio_out))
      (Cyclesim.Reg.to_int cnt1)
  in
  inp.rst_n := Bits.of_unsigned_int ~width:1 0;
  Cyclesim.cycle sim;
  inp.rst_n := Bits.of_unsigned_int ~width:1 1;
  for _ = 1 to 39 do
    Cyclesim.cycle sim
  done;
  show "configured:";
  (* the button: hold reset across a tick (cycle 50) and sample with rst_n still low *)
  inp.rst_n := Bits.of_unsigned_int ~width:1 0;
  for _ = 1 to 12 do
    Cyclesim.cycle sim
  done;
  show "in reset:  ";
  inp.rst_n := Bits.of_unsigned_int ~width:1 1;
  [%expect
    {|
    configured: leds=0xAB spi_ctrl=0x5 gpoc=0xFF | survivors: gpout=0x3C cnt1=4
    in reset:   leds=0x0 spi_ctrl=0x0 gpoc=0x0 | survivors: gpout=0x3C cnt1=5
    |}]
;;

let%expect_test "soc — video DMA: vidreq steals a core cycle and steers the SRAM" =
  let module Sim = Cyclesim.With_interface (I) (O) in
  let nop = 0x40080000 in
  (* A long run of single-cycle instructions, so that [pc] counts instructions and only
     the video stall can hold it. (In this one-domain simulation the pixel raster advances
     once per [clk].) *)
  let sim =
    Sim.create
      ~config:Cyclesim.Config.trace_all
      (create ~contents:(Array.create ~len:400 nop))
  in
  let inp = Cyclesim.inputs sim in
  let node name =
    match Cyclesim.lookup_node_or_reg_by_name sim name with
    | Some n -> n
    | None -> failwith ("soc video test: no traced node " ^ name)
  in
  let pc = Option.value_exn (Cyclesim.lookup_reg_by_name sim "pc") in
  let vidreq = node "vidreq"
  and sram_adr = node "sram_adr"
  and vidadr = node "vidadr" in
  inp.rst_n := Bits.of_unsigned_int ~width:1 0;
  Cyclesim.cycle sim;
  inp.rst_n := Bits.of_unsigned_int ~width:1 1;
  (* fill the pipeline so [pc] is moving, then measure a clean window *)
  for _ = 1 to 4 do
    Cyclesim.cycle sim
  done;
  let pc0 = Cyclesim.Reg.to_int pc in
  let n = 200 in
  let stalls = ref 0
  and addr_ok = ref true in
  for _ = 1 to n do
    Cyclesim.cycle sim;
    if Cyclesim.Node.to_int vidreq = 1
    then (
      Int.incr stalls;
      (* on a steal cycle the shared port carries the framebuffer word [vidadr << 2] *)
      if Cyclesim.Node.to_int sram_adr <> Cyclesim.Node.to_int vidadr * 4
      then addr_ok := false)
  done;
  let pc1 = Cyclesim.Reg.to_int pc in
  Stdlib.Printf.printf
    "over %d cycles: vidreq pulses=%d (>0 %b)\n\
     pc advanced=%d; advanced+stalls=%d (≈ cycles)\n\
     SRAM steered to vidadr<<2 on every steal: %b\n"
    n
    !stalls
    (!stalls > 0)
    (pc1 - pc0)
    (pc1 - pc0 + !stalls)
    !addr_ok;
  [%expect
    {|
    over 200 cycles: vidreq pulses=6 (>0 true)
    pc advanced=194; advanced+stalls=200 (≈ cycles)
    SRAM steered to vidadr<<2 on every steal: true
    |}]
;;

let%expect_test "soc — UART loopback through MMIO words 2/3" =
  let module Sim = Cyclesim.With_interface (I) (O) in
  let nop = 0x40080000 in
  (* Set the fast rate, transmit 0x5A, poll until a byte has been received, and read it
     back. [rxd] is looped to [txd] by the test. *)
  let prog =
    [| 0x610000FF (* MOV' R1, #0xFF<<16 R1 = 0xFF0000 *)
     ; 0x4216FFC8 (* IOR R2, R1, #0xFFC8 R2 = 0xFFFFC8 (word 2, UART data) *)
     ; 0x4316FFCC (* IOR R3, R1, #0xFFCC R3 = 0xFFFFCC (word 3, UART status/ctrl) *)
     ; 0x44000001 (* MOV R4, #1 *)
     ; 0xA4300000 (* ST R4, [R3] bitrate := 1 (115200) *)
     ; 0x4500005A (* MOV R5, #0x5A *)
     ; 0xA5200000 (* ST R5, [R2] startTx, dataTx = 0x5A *)
     ; 0x86300000 (* LD   R6, [R3]          R6 = {rdyTx, rdyRx}        <- poll *)
     ; 0x47640001 (* AND R7, R6, #1 R7 = rdyRx; Z = (rdyRx==0) *)
     ; 0xE1FFFFFD (* BEQ -3 while rdyRx==0, back to the LD *)
     ; 0x80200000 (* LD R0, [R2] R0 = dataRx (pulses doneRx) *)
     ; nop
    |]
  in
  let sim = Sim.create ~config:Cyclesim.Config.trace_all (create ~contents:prog) in
  let inp = Cyclesim.inputs sim in
  let outp = Cyclesim.outputs sim in
  let regfile = Option.value_exn (Cyclesim.lookup_mem_by_name sim "regfile") in
  let lo = Bits.gnd
  and hi = Bits.vdd in
  inp.rst_n := lo;
  inp.rxd := hi (* idle high *);
  Cyclesim.cycle sim;
  inp.rst_n := hi;
  (* ~10 bit-times × 217 cycles + setup/poll; loop the serial line back each cycle *)
  for _ = 1 to 5000 do
    inp.rxd := !(outp.txd);
    Cyclesim.cycle sim
  done;
  (* R6 holds the status word of the poll that left the loop: rdyRx (bit 0) is up while
     the transmitter is still on its stop bit (rdyTx, bit 1, down) — which pins the order
     of the two status bits, not just that one of them rose *)
  Stdlib.Printf.printf
    "R0 (UART data_rx, loopback of 0x5A) = 0x%X\n\
     R6 (status {rdyTx, rdyRx} at loop exit) = 0x%X\n"
    (Cyclesim.Memory.to_int regfile ~address:0)
    (Cyclesim.Memory.to_int regfile ~address:6);
  [%expect
    {|
    R0 (UART data_rx, loopback of 0x5A) = 0x5A
    R6 (status {rdyTx, rdyRx} at loop exit) = 0x1
    |}]
;;

let%expect_test "soc — PS/2 keyboard: a scancode frame surfaces at words 6/7" =
  let module Sim = Cyclesim.With_interface (I) (O) in
  let nop = 0x40080000 in
  (* Poll word 6 bit 28 (rdyKbd) — [LSL #3] lifts it to the sign bit, [BPL] loops while
     clear — then read the byte from word 7. The word-6 value captured at exit doubles as
     a structural check: rdyKbd at bit 28, mouse state (idle = 0) in [27:0], top 3 bits
     zero. (The mouse's own outputs/accumulation are covered by mouse.ml + its cosim.) *)
  let prog =
    [| 0x610000FF (* MOV' R1, #0xFF<<16 R1 = 0xFF0000 *)
     ; 0x4216FFD8 (* IOR R2, R1, #0xFFD8 R2 = 0xFFFFD8 (word 6) *)
     ; 0x4316FFDC (* IOR R3, R1, #0xFFDC R3 = 0xFFFFDC (word 7) *)
     ; 0x84200000 (* LD   R4, [R2]          R4 = {rdyKbd, dataMs}    <- poll *)
     ; 0x45410003 (* LSL R5, R4, #3 bit 28 -> bit 31; N = rdyKbd *)
     ; 0xE8FFFFFD (* BPL -3 while rdyKbd==0, back to the LD *)
     ; 0x80300000 (* LD R0, [R3] R0 = keyboard byte (pops the FIFO) *)
     ; nop
    |]
  in
  let sim = Sim.create ~config:Cyclesim.Config.trace_all (create ~contents:prog) in
  let inp = Cyclesim.inputs sim in
  let regfile = Option.value_exn (Cyclesim.lookup_mem_by_name sim "regfile") in
  let b1 v = Bits.of_unsigned_int ~width:1 v in
  (* Drive a device->host PS/2 frame ([Ps2.For_tests.frame_bits]). [ps2c] idles high; the
     module samples [ps2d] on each ps2c falling edge (2-FF synchronized), so hold each
     level a few clk cycles. The CPU runs throughout. *)
  let feed_bit b =
    inp.ps2d := b1 (Bool.to_int b);
    inp.ps2c := b1 1;
    for _ = 1 to 4 do
      Cyclesim.cycle sim
    done;
    inp.ps2c := b1 0;
    for _ = 1 to 4 do
      Cyclesim.cycle sim
    done
  in
  let feed_byte byte = List.iter (Ps2.For_tests.frame_bits byte) ~f:feed_bit in
  inp.rst_n := b1 0;
  inp.ps2c := b1 1;
  inp.ps2d := b1 1;
  inp.msclk := b1 1;
  inp.msdat := b1 1 (* mouse idle: open-drain lines released *);
  Cyclesim.cycle sim;
  inp.rst_n := b1 1;
  feed_byte 0x1C;
  for _ = 1 to 60 do
    Cyclesim.cycle sim
  done;
  let r k = Cyclesim.Memory.to_int regfile ~address:k in
  Stdlib.Printf.printf
    "word6 @rdyKbd = 0x%X (rdyKbd=bit28, mouse=0)   R0 (word7 scancode) = 0x%X\n"
    (r 4)
    (r 0);
  [%expect
    {| word6 @rdyKbd = 0x10000000 (rdyKbd=bit28, mouse=0)   R0 (word7 scancode) = 0x1C |}]
;;
